### ISSUE TITLE
Adding FSI autocomplete API

### ISSUE THREAD

**Issue by tpetricek** [ionide/FsInteractiveService#2]
This is probably not directly relevant to Ionide (we're far from having FSI autocomplete), but it could be nice to support this for other editors. Jason did lots of work on this for XS, so this is just to track some basic info about what we need to add.

 - F# Interactive service in XS is here: https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/master/MonoDevelop.FSharpi.Service/Program.fs
 - It calls some functions from https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/cb7ea0814ce61af6771d0b5ebb57ec4dabb748b0/MonoDevelop.FSharp.Shared/Completions.fs (and generally the shared folder)

How it works:

 - `input let x = 1` - The `input` command evals input
 - `tooltip List.map` - Get tooltip (for fully qualified complete name - also variables defined before)
 - `completion 3 Lis` - get completion at column 3 for prefix List (can have more text afterwards too)
 - `parameter-hints 0 head` - (bit weird :)) you have to run `completion` first - this then searches for `head` in the completions and returns - some sort of hint :) TBD

/cc @nosami @enricosada

**Comment by tpetricek** [comment]
I started looking into this...

@nosami - one question - what do you think is the best long term plan for sharing the code? I just copied the files for now, but they look like a basic set of things that would be nice to share in some way. Should we have one home for them & use Paket file dependencies? Or some reusable component? Or just copy & edit as needed?

**Comment by nosami** [comment]
Would make sense for the code to be centralised somewhere. Think I'd like to use it as a binary dependency but happy to go along with whatever you guys think is best.

Seem to remember you saying that you'd like to add a Suave wrapper. So long as that is separate from the rest, then anything else is fine.

**Comment by nosami** [comment]
Most of the code was copied from monodevelop and then all the monodevelop stuff was stripped out. There are some oddities in the code as a result of this...e.g [these blocks](https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/cb7ea0814ce61af6771d0b5ebb57ec4dabb748b0/MonoDevelop.FSharp.Shared/FSharpSymbolHelper.fs#L344-L353) used to contain syntax highlighting code

**Comment by tpetricek** [comment]
Sounds good. I have (quite astonishingly) done some Git magic and imported your shared folder into this project (!) with history (!!): https://github.com/ionide/FsInteractiveService/compare/master...tpetricek:master2

**Comment by tpetricek** [comment]
@nosami Do you have user id on nuget.org, so that I can add you as a co-owner of the package?

**Comment by nosami** [comment]
@tpetricek Yes. It's `jasonimison`. Thanks!

**Comment by tpetricek** [comment]
@nosami Added you as owner for the [http packge](https://www.nuget.org/packages/FsInteractiveService.HTTP) and the [shared package](https://www.nuget.org/packages/FsInteractiveService.Shared), so that you can release both when you make changes. You should now also have admin rights for this repo.

The shared package is pretty much exactly what you had in the Shared project in Xamarin. The only change I did is that I removed the mutation that was remembering state after calling `completion` (so that it is available when calling `tooltip`). The `getCompletions` function now [returns symbols](https://github.com/ionide/FsInteractiveService/blob/master/src/FsInteractiveService/Main.fs#L272) that you [need to pass](https://github.com/ionide/FsInteractiveService/blob/master/src/FsInteractiveService/Main.fs#L292) to `getCompletionTooltips`.

I have not ported the standard I/O based interface to this project yet, but it would be awesome to add that for the Emacs fans here. I have some other more high-priority things, but would be happy to help if needed.

@enricosada If you want to replace F# Interactive in VS with something awesome, you should now have all you need :-) check out the new docs:

 - [Running snippets via HTTP API](http://ionide.io/FsInteractiveService/http.html)
 - [Getting IntelliSense via HTTP API](http://ionide.io/FsInteractiveService/intelli.html)

**Comment by nosami** [comment]
nice work!
